apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
      - image: niels58/java-demo:pe-master-21
        name: java-demo
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: 512m
            memory: 256Mi
          requests:
            cpu: 200m
            memory: 256Mi
      restartPolicy: Always
