apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: spring-boot
  name: spring-boot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-boot
  template:
    metadata:
      labels:
        app: spring-boot
    spec:
      containers:
        - image: niels58/java-demo:pe-master-30
          name: spring-boot
          ports:
            - containerPort: 8080
          resources: 
            requests:
              cpu: 200m
              memory: 256Mi
            limits:
              memory: 256Mi
              cpu: 512m
      restartPolicy: Always
